{% set name = "pyigd" %}
{% set version = "1.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 3c7c1a13af13e16d4b4b6a8930a22cf032e3751ce98d18d2126e93eb2b3f60e4

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - pyigd

about:
  home: "https://aprilweilab.github.io/"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Parser for IGD files"
  doc_url: "https://pyigd.readthedocs.io/en/latest/index.html"
  dev_url: "https://github.com/aprilweilab/pyigd"

extra:
  recipe-maintainers:
    - dcdehaas
